name: Install XAMPP on Server

on:
  workflow_dispatch # This allows you to manually trigger the workflow from the GitHub UI

jobs:
  install-xampp:
    name: Install XAMPP
    runs-on: self-hosted # Uses your runner at 192.168.0.129

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XAMPP via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Update package list
            sudo apt-get update -y

            # Download the latest XAMPP for Linux (always check https://www.apachefriends.org/download.html for the latest version)
            wget -O xampp-installer.run "https://sourceforge.net/projects/xampp/files/XAMPP%20Linux/8.2.12/xampp-linux-x64-8.2.12-0-installer.run/download"

            # Make the installer executable
            chmod +x xampp-installer.run

            # Run the installer in unattended mode
            # The --mode unattended option will use the default settings
            sudo ./xampp-installer.run --mode unattended

            # Clean up the installer file
            rm xampp-installer.run

            # Start the XAMPP stack (Apache and MySQL)
            sudo /opt/lampp/lampp start
